Repository dhtmdwo/Matfia-Eatzzy-Back, pull requests merged in 2025-02, with the labels that each got.

#45 [Feat] 식당 엔티티 생성, 식당 등록 기능 구현
  matfiaBack/app-api/build.gradle
  matfiaBack/app-api/src/main/java/com/example/appapi/store/StoreClosedDayRepository.java
  matfiaBack/app-api/src/main/java/com/example/appapi/store/StoreController.java
  matfiaBack/app-api/src/main/java/com/example/appapi/store/StoreRepository.java
  matfiaBack/app-api/src/main/java/com/example/appapi/store/StoreService.java
  matfiaBack/app-api/src/main/java/com/example/appapi/store/model/AllowedStatus.java
  matfiaBack/app-api/src/main/java/com/example/appapi/store/model/Store.java
  matfiaBack/app-api/src/main/java/com/example/appapi/store/model/StoreClosedDay.java
  matfiaBack/app-api/src/main/java/com/example/appapi/store/model/StoreDto.java
Labels: feature

#50 [Feat] 리뷰 엔티티 생성, 리뷰 작성 기능 구현
  app-api/src/main/java/com/example/appapi/reviews/ReviewsController.java
  app-api/src/main/java/com/example/appapi/reviews/ReviewsRepository.java
  app-api/src/main/java/com/example/appapi/reviews/ReviewsService.java
  app-api/src/main/java/com/example/appapi/reviews/model/Reviews.java
  app-api/src/main/java/com/example/appapi/reviews/model/ReviewsDto.java
Labels: feature

#55 [Feat] 리뷰 목록 조회 기능 구현
  app-api/src/main/java/com/example/appapi/reviews/ReviewsController.java
  app-api/src/main/java/com/example/appapi/reviews/ReviewsService.java
  app-api/src/main/java/com/example/appapi/reviews/model/ReviewsDto.java
Labels: feature

#56 [Chore] 폴더 구조 수정
  matfiaBack/app-api/src/main/java/com/example/appapi/paymentmethod/PaymentMethodController.java
  matfiaBack/app-api/src/main/java/com/example/appapi/paymentmethod/PaymentMethodRepository.java
  matfiaBack/app-api/src/main/java/com/example/appapi/paymentmethod/PaymentMethodService.java
  matfiaBack/app-api/src/main/java/com/example/appapi/paymentmethod/model/PaymentMethod.java
  matfiaBack/app-api/src/main/java/com/example/appapi/paymentmethod/model/PaymentMethodDto.java
  matfiaBack/app-api/src/main/java/com/example/appapi/reviews/ReviewsController.java
  matfiaBack/app-api/src/main/java/com/example/appapi/reviews/ReviewsRepository.java
  matfiaBack/app-api/src/main/java/com/example/appapi/reviews/ReviewsService.java
  matfiaBack/app-api/src/main/java/com/example/appapi/reviews/model/Reviews.java
  matfiaBack/app-api/src/main/java/com/example/appapi/reviews/model/ReviewsDto.java
Labels: chore

#65 [Feat] BaseResponse, 에러 처리 구현
  common/src/main/java/com/example/BaseException.java
  common/src/main/java/com/example/common/BaseResponse.java
  common/src/main/java/com/example/common/BaseResponseStatus.java
Labels: feature

#67 [Feat] 예외처리 구현
  common/src/main/java/com/example/common/BaseResponse.java
  common/src/main/java/com/example/common/exception/BaseException.java
  common/src/main/java/com/example/common/exception/GlobalExceptionHandler.java
Labels: feature

#75 common 모듈 설정 수정, 예외처리 status 수정
  app-api/build.gradle
  common/src/main/java/com/example/common/BaseResponseStatus.java
  common/src/main/resources/application.properties
  common/src/main/resources/application.yml
  resv-api/build.gradle
Labels: fix

#77 [Fix] 식당 생성 기능 return 타입 변경
  app-api/src/main/java/com/example/appapi/store/StoreController.java
  app-api/src/main/java/com/example/appapi/store/StoreService.java
  app-api/src/main/java/com/example/appapi/store/model/StoreDto.java
Labels: fix

#94 [Feat] 식당 조회 기능 구현, 카테고리 구현
  app-api/src/main/java/com/example/appapi/category/CategoryController.java
  app-api/src/main/java/com/example/appapi/category/CategoryRepository.java
  app-api/src/main/java/com/example/appapi/category/CategoryService.java
  app-api/src/main/java/com/example/appapi/category/model/Category.java
  app-api/src/main/java/com/example/appapi/category/model/CategoryDto.java
  app-api/src/main/java/com/example/appapi/store/StoreController.java
  app-api/src/main/java/com/example/appapi/store/StoreRepository.java
  app-api/src/main/java/com/example/appapi/store/StoreService.java
  app-api/src/main/java/com/example/appapi/store/model/Store.java
  app-api/src/main/java/com/example/appapi/store/model/StoreDto.java
  app-api/src/main/resources/application.yml
Labels: feature

#95 [Fix] Store 엔티티 수정
  app-api/src/main/java/com/example/appapi/store/model/Store.java
Labels: fix

#96 [Feat] 카테고리 조회 기능 구현
  app-api/src/main/java/com/example/appapi/category/CategoryController.java
  app-api/src/main/java/com/example/appapi/category/CategoryRepository.java
  app-api/src/main/java/com/example/appapi/category/CategoryService.java
  app-api/src/main/java/com/example/appapi/category/model/Category.java
  app-api/src/main/java/com/example/appapi/category/model/CategoryDto.java
Labels: feature

#99 [Feature] StoreReview 엔티티 생성
  app-api/src/main/java/com/example/appapi/store/review/StoreReviewController.java
  app-api/src/main/java/com/example/appapi/store/review/StoreReviewRepository.java
  app-api/src/main/java/com/example/appapi/store/review/StoreReviewService.java
  app-api/src/main/java/com/example/appapi/store/review/model/StoreReview.java
  app-api/src/main/java/com/example/appapi/store/review/model/StoreReviewDto.java
Labels: feature

#100 [Feature] StoreReviewImage 엔티티 생성, 연관관계 매핑
  app-api/src/main/java/com/example/appapi/store/review/StoreReviewController.java
  app-api/src/main/java/com/example/appapi/store/review/StoreReviewRepository.java
  app-api/src/main/java/com/example/appapi/store/review/StoreReviewService.java
  app-api/src/main/java/com/example/appapi/store/review/controller/StoreReviewController.java
  app-api/src/main/java/com/example/appapi/store/review/model/StoreReview.java
  app-api/src/main/java/com/example/appapi/store/review/model/StoreReviewImage.java
  app-api/src/main/java/com/example/appapi/store/review/repository/StoreReviewImageRepository.java
  app-api/src/main/java/com/example/appapi/store/review/repository/StoreReviewRepository.java
  app-api/src/main/java/com/example/appapi/store/review/service/StoreReviewService.java
  app-api/src/main/java/com/example/appapi/store/review/service/StoreReviewimageService.java
Labels: feature

#101 [Feature] 식당 리뷰 작성, 조회 기능 구현
  app-api/src/main/java/com/example/appapi/store/review/model/StoreReviewDto.java
  app-api/src/main/java/com/example/appapi/store/review/service/StoreReviewImageService.java
  app-api/src/main/java/com/example/appapi/store/review/service/StoreReviewService.java
  app-api/src/main/java/com/example/appapi/store/review/service/StoreReviewimageService.java
Labels: feature
